### PR TITLE
Correct CS on SPI1 pin

### PR DESCRIPTION
**Pull request by rngkll**
Hi Dan,

I changed the pin number for SPI1 CS to the correct one specified in the board specification, figure 14, page 36.

http://www.st.com/st-web-ui/static/active/cn/resource/technical/document/user_manual/DM00039084.pdf

Thanks,

### CODE REVIEW

**Comment by ddrown** [comment]
I agree that this define should be changed to this value.  The problem is the unknown (possibly zero) number of people depending on this define's current value.

I've started a thread here: http://stm32duino.com/viewtopic.php?f=39&t=1060

**Comment by martinayotte** [comment]
The PE3 pin is only available on LQFP100 package, not on any LQFP64, therefore, maybe this change should only be apply do the DISCOVERY board using the define "BOARD_discovery_f4".

**Comment by rngkll** [comment]
Thanks for the info, I'll do the change.

**Comment by martinayotte** [comment]
@rngkll, maybe you can take a look about this thread : http://stm32duino.com/viewtopic.php?f=39&p=12886&sid=e34e052a88180b20ac4aef14ca2d381f#p12886
I think we need to create new "GenericF4" variant, and then doing #ifdef on the "BOARD_discovery_f4" define.

**Comment by rngkll** [comment]
Hi,

Thanks, I'm reading the thread.

Is there a place to chat, ask questions and have discussions, something like a IRC specific to stm32duino?

**Comment by martinayotte** [comment]
No chat ! only the forum ...

**Pull request closed without merging**
